# Generated by Django 5.2.6 on 2025-09-19 02:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_user_appuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("admins", models.TextField(null=True)),
                ("members", models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="team",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="email",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="password",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="website",
        ),
        migrations.AddField(
            model_name="appuser",
            name="devices",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="encrypted_private_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="kdf",
            field=models.CharField(default="argon2id", max_length=50),
        ),
        migrations.AddField(
            model_name="appuser",
            name="kdf_salt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="public_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="team_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="acl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="assigned_to_team_ids",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="cipher_algo",
            field=models.CharField(default="xchacha20-poly1305", max_length=50),
        ),
        migrations.AddField(
            model_name="credential",
            name="ciphertext",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="credential",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="credential",
            name="meta",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="owner_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="credential",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="credential",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
    ]
