# Generated by Django 5.2.6 on 2025-09-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_remove_appuser_team_remove_credential_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='kdf_nonce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='devices',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='acl',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='assigned_to_team_ids',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='meta',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='team',
            name='admins',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.TextField(default='[]'),
        ),
    ]
